package api

import "github.com/gorilla/mux"

func registerBaseRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/health", s.handleHealth).Methods("GET", "OPTIONS")
	r.HandleFunc("/openapi.yaml", s.handleOpenAPIYAML).Methods("GET", "OPTIONS")
	r.HandleFunc("/openapi.json", s.handleOpenAPIJSON).Methods("GET", "OPTIONS")
	r.HandleFunc("/openapi/v1.json", s.handleOpenAPIV1JSON).Methods("GET", "OPTIONS")
	r.HandleFunc("/openapi/v2.json", s.handleOpenAPIV2JSON).Methods("GET", "OPTIONS")
	r.HandleFunc("/status", s.handleStatus).Methods("GET", "OPTIONS")
	r.HandleFunc("/ws", s.handleWebSocket).Methods("GET", "OPTIONS")
	r.HandleFunc("/ws/status", s.handleStatusWebSocket).Methods("GET", "OPTIONS")
}

func registerLegacyRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/blocks", s.handleListBlocks).Methods("GET", "OPTIONS")
	r.HandleFunc("/blocks/{id}", s.handleGetBlock).Methods("GET", "OPTIONS")
	r.HandleFunc("/transactions", s.handleListTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/transactions/{id}", s.handleGetTransaction).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}", s.handleGetAccount).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/transactions", s.handleGetAccountTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/token-transfers", s.handleGetAccountTokenTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/nft-transfers", s.handleGetAccountNFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/scheduled-transactions", s.handleGetAccountScheduledTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/stats", s.handleGetAddressStats).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/contract", s.handleGetContractByAddress).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/contracts/{name}", s.handleGetAccountContractCode).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/storage", s.handleGetAccountStorage).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/storage/links", s.handleGetAccountStorageLinks).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounts/{address}/storage/item", s.handleGetAccountStorageItem).Methods("GET", "OPTIONS")
	r.HandleFunc("/stats/daily", s.handleGetDailyStats).Methods("GET", "OPTIONS")
	r.HandleFunc("/stats/network", s.handleGetNetworkStats).Methods("GET", "OPTIONS")
	r.HandleFunc("/keys/{publicKey}", s.handleGetAddressByPublicKey).Methods("GET", "OPTIONS")
	r.HandleFunc("/coa/{address}", s.handleGetCOAMapping).Methods("GET", "OPTIONS")
}

func registerV1Routes(r *mux.Router, s *Server) {
	registerFlowRoutes(r, s)
	registerAccountingRoutes(r, s)
	registerStatusRoutes(r, s)
	registerDeferredRoutes(r, s)
	registerCompatibilityRoutes(r, s)
}

func registerV2Routes(r *mux.Router, s *Server) {
	registerFlowRoutes(r, s)
	registerAccountingRoutes(r, s)
	registerStatusRoutes(r, s)
	registerDeferredRoutes(r, s)
}

func registerFlowRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/flow/v1/block", s.handleFlowListBlocks).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/block/{height}", s.handleFlowGetBlock).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/block/{height}/service-event", s.handleFlowBlockServiceEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/block/{height}/transaction", s.handleFlowBlockTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/transaction", s.handleFlowListTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/transaction/{id}", s.handleFlowGetTransaction).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account", s.handleFlowListAccounts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}", s.handleFlowGetAccount).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/transaction", s.handleFlowAccountTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/ft/transfer", s.handleFlowAccountFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/nft/transfer", s.handleFlowAccountNFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/ft/holding", s.handleFlowAccountFTHoldings).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/ft", s.handleFlowAccountFTVaults).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/ft/{token}", s.handleFlowAccountFTToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/ft/{token}/transfer", s.handleFlowAccountFTTokenTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/nft", s.handleFlowAccountNFTCollections).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/nft/{nft_type}", s.handleFlowAccountNFTByCollection).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/ft/transfer", s.handleFlowFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/ft", s.handleFlowListFTTokens).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/ft/{token}", s.handleFlowGetFTToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/ft/{token}/holding", s.handleFlowFTHoldingsByToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/ft/{token}/top-account", s.handleFlowTopFTAccounts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/ft/{token}/account/{address}", s.handleFlowAccountFTHoldingByToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/nft/transfer", s.handleFlowNFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/nft", s.handleFlowListNFTCollections).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/nft/{nft_type}", s.handleFlowGetNFTCollection).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/nft/{nft_type}/holding", s.handleFlowNFTHoldingsByCollection).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/nft/{nft_type}/top-account", s.handleFlowTopNFTAccounts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/nft/{nft_type}/item/{id}", s.handleFlowNFTItem).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/nft/{nft_type}/item/{id}/transfer", s.handleFlowNFTItemTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/contract", s.handleFlowListContracts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/contract/{identifier}", s.handleFlowGetContract).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/contract/{identifier}/transaction", s.handleContractTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/contract/{identifier}/version", s.handleContractVersionList).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/contract/{identifier}/version/{id}", s.handleFlowGetContractVersion).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/contract/{identifier}/{id}", s.handleFlowGetContractVersion).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/evm/transaction", s.handleFlowListEVMTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/evm/transaction/{hash}", s.handleFlowGetEVMTransaction).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/evm/token", s.handleFlowListEVMTokens).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/evm/token/{address}", s.handleFlowGetEVMToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/node", s.handleListNodes).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/node/{node_id}", s.handleGetNode).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/node/{node_id}/reward/delegation", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/scheduled-transaction", s.handleFlowScheduledTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/scheduled-transaction", s.handleFlowAccountScheduledTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/v1/account/{address}/tax-report", s.handleTaxReport).Methods("GET", "OPTIONS")
}

func registerAccountingRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/accounting/v1/account/{address}", s.handleFlowGetAccount).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/account/{address}/transaction", s.handleFlowAccountTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/account/{address}/ft/transfer", s.handleFlowAccountFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/account/{address}/nft", s.handleFlowAccountNFTCollections).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/account/{address}/ft", s.handleFlowAccountFTVaults).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/transaction", s.handleFlowListTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/transaction/{id}", s.handleFlowGetTransaction).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/nft/transfer", s.handleFlowNFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/v1/account/{address}/tax-report", s.handleTaxReport).Methods("GET", "OPTIONS")
}

func registerStatusRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/status/v1/count", s.handleStatusCount).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/v1/stat", s.handleStatusStat).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/v1/stat/{timescale}/trend", s.handleStatusStatTrend).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/v1/flow/stat", s.handleStatusFlowStat).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/v1/epoch/status", s.handleStatusEpochStatus).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/v1/epoch/stat", s.handleStatusEpochStat).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/v1/tokenomics", s.handleStatusTokenomics).Methods("GET", "OPTIONS")
}

func registerDeferredRoutes(r *mux.Router, s *Server) {
	// DeFi endpoints (Phase 8)
	r.HandleFunc("/defi/v1/asset", s.handleDefiListAssets).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/v1/events", s.handleDefiListEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/v1/latest-block", s.handleDefiLatestBlock).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/v1/latest-swap", s.handleDefiLatestSwap).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/v1/pair", s.handleDefiListPairs).Methods("GET", "OPTIONS")
	// Staking endpoints (Phase 7)
	r.HandleFunc("/staking/v1/delegator", s.handleStakingDelegators).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/account/{address}/ft/transfer", s.handleStakingAccountFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/account/{address}/transaction", s.handleStakingAccountTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/epoch/stats", s.handleGetEpochStats).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/epoch/{epoch}/nodes", s.handleListEpochNodes).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/epoch/{epoch}/role/{role}/nodes/aggregate", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/epoch/{epoch}/role/{role}/nodes/count", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/epoch/{epoch}/role/{role}/nodes/grouped", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/ft_transfer/{address}", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/node/{node_id}/event", s.handleGetNodeEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/rewards/paid", s.handleStakingRewardsPaid).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/rewards/staking", s.handleStakingRewardsStaking).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/tokenomics", s.handleStakingTokenomics).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/transaction/address/{address}", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/v1/transaction/{transaction_id}", s.handleNotImplemented).Methods("GET", "OPTIONS")
}

func registerCompatibilityRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/auth/v1/generate", s.handleNotImplemented).Methods("POST", "OPTIONS")
	r.HandleFunc("/bulk/v1/contract", s.handleBulkListContracts).Methods("GET", "OPTIONS")
	// NFT/v0 endpoints (Phase 7)
	r.HandleFunc("/nft/v0/{nft_type}/holding", s.handleNFTV0Holding).Methods("GET", "OPTIONS")
	r.HandleFunc("/nft/v0/{nft_type}/item", s.handleNFTV0Item).Methods("GET", "OPTIONS")
	r.HandleFunc("/nft/v0/{nft_type}/item/{nft_id}", s.handleNFTV0ItemByID).Methods("GET", "OPTIONS")
	r.HandleFunc("/public/v1/account/{address}", s.handlePublicGetAccount).Methods("GET", "OPTIONS")
	r.HandleFunc("/public/v1/epoch/payout", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/public/v1/resolver", s.handleNotImplemented).Methods("GET", "OPTIONS")
	// Simple/v1 endpoints (Phase 7)
	r.HandleFunc("/simple/v1/blocks", s.handleSimpleBlocks).Methods("GET", "OPTIONS")
	r.HandleFunc("/simple/v1/events", s.handleSimpleEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/simple/v1/node_rewards", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/simple/v1/rewards", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/simple/v1/transaction", s.handleSimpleTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/simple/v1/transaction/events", s.handleSimpleTransactionEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/triggers/v1/logs", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/triggers/v1/triggers", s.handleNotImplemented).Methods("GET", "POST", "OPTIONS")
	r.HandleFunc("/triggers/v1/triggers/{id}", s.handleNotImplemented).Methods("GET", "PUT", "DELETE", "OPTIONS")
	r.HandleFunc("/triggers/v1/triggers/{id}/status", s.handleNotImplemented).Methods("PATCH", "OPTIONS")
	r.HandleFunc("/triggers/v1/requeue/{id}", s.handleNotImplemented).Methods("POST", "OPTIONS")
	r.HandleFunc("/wallet/v1/participation/{address}", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/wallet/v1/participation/{address}/aggregate", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/wallet/v1/participation/{address}/count", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/wallet/v1/participation/{address}/{token}", s.handleNotImplemented).Methods("GET", "OPTIONS")
}
