package api

import (
	"time"

	"github.com/gorilla/mux"
)

func registerBaseRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/health", s.handleHealth).Methods("GET", "OPTIONS")
	r.HandleFunc("/openapi.yaml", s.handleOpenAPIYAML).Methods("GET", "OPTIONS")
	r.HandleFunc("/openapi.json", s.handleOpenAPIJSON).Methods("GET", "OPTIONS")
	r.HandleFunc("/status", s.handleStatus).Methods("GET", "OPTIONS")
	r.HandleFunc("/ws", s.handleWebSocket).Methods("GET", "OPTIONS")
	r.HandleFunc("/ws/status", s.handleStatusWebSocket).Methods("GET", "OPTIONS")
}

func registerAdminRoutes(r *mux.Router, s *Server) {
	admin := r.PathPrefix("/admin").Subrouter()
	admin.Use(adminAuthMiddleware)
	admin.HandleFunc("/refetch-token-metadata", s.handleAdminRefetchTokenMetadata).Methods("POST", "OPTIONS")
	admin.HandleFunc("/batch-fetch-metadata", s.handleAdminBatchFetchMetadata).Methods("POST", "OPTIONS")
	admin.HandleFunc("/refetch-bridge", s.handleAdminRefetchBridge).Methods("POST", "OPTIONS")
	admin.HandleFunc("/ft", s.handleAdminListFTTokens).Methods("GET", "OPTIONS")
	admin.HandleFunc("/ft/{identifier}", s.handleAdminUpdateFTToken).Methods("PUT", "PATCH", "OPTIONS")
	admin.HandleFunc("/nft", s.handleAdminListNFTCollections).Methods("GET", "OPTIONS")
	admin.HandleFunc("/nft/{identifier}", s.handleAdminUpdateNFTCollection).Methods("PUT", "PATCH", "OPTIONS")
	admin.HandleFunc("/import-token/preview", s.handleAdminImportTokenPreview).Methods("POST", "OPTIONS")
	admin.HandleFunc("/import-token/save", s.handleAdminSaveImportedToken).Methods("POST", "OPTIONS")
	admin.HandleFunc("/script-templates", s.handleAdminListScriptTemplates).Methods("GET", "OPTIONS")
	admin.HandleFunc("/script-templates/stats", s.handleAdminGetScriptTemplateStats).Methods("GET", "OPTIONS")
	admin.HandleFunc("/script-templates/refresh-counts", s.handleAdminRefreshScriptTemplateCounts).Methods("POST", "OPTIONS")
	admin.HandleFunc("/script-templates/ai-classify", s.handleAdminAIClassify).Methods("POST", "OPTIONS")
	admin.HandleFunc("/script-templates/ai-classify-batch", s.handleAdminAIClassifyBatch).Methods("POST", "OPTIONS")
	admin.HandleFunc("/script-templates/{hash}", s.handleAdminUpdateScriptTemplate).Methods("PUT", "PATCH", "OPTIONS")
	admin.HandleFunc("/script-templates/{hash}/script", s.handleAdminGetScriptText).Methods("GET", "OPTIONS")
	admin.HandleFunc("/reset-token-worker", s.handleAdminResetTokenWorker).Methods("POST", "OPTIONS")
	admin.HandleFunc("/reset-history-deriver", s.handleAdminResetHistoryDeriver).Methods("POST", "OPTIONS")
	admin.HandleFunc("/redirect-history-ingester", s.handleAdminRedirectHistoryIngester).Methods("POST", "OPTIONS")
	admin.HandleFunc("/resolve-errors", s.handleAdminResolveErrors).Methods("POST", "OPTIONS")
	admin.HandleFunc("/skipped-ranges", s.handleAdminListSkippedRanges).Methods("GET", "OPTIONS")
	admin.HandleFunc("/backfill-staking", s.handleAdminBackfillStakingBlocks).Methods("POST", "OPTIONS")
	admin.HandleFunc("/account-labels", s.handleAdminListAccountLabels).Methods("GET", "OPTIONS")
	admin.HandleFunc("/account-labels", s.handleAdminUpsertAccountLabel).Methods("POST", "PUT", "OPTIONS")
	admin.HandleFunc("/account-labels/{address}/{tag}", s.handleAdminDeleteAccountLabel).Methods("DELETE", "OPTIONS")
}

func registerAPIRoutes(r *mux.Router, s *Server) {
	registerFlowRoutes(r, s)
	registerAccountingRoutes(r, s)
	registerStatusRoutes(r, s)
	registerDeferredRoutes(r, s)
	registerAIRoutes(r, s)
}

func registerAIRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/ai/tx-summary", s.handleAITxSummary).Methods("POST", "OPTIONS")
}

func registerFlowRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/flow/block", s.handleFlowListBlocks).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/block/{height}", s.handleFlowGetBlock).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/block/{height}/service-event", s.handleFlowBlockServiceEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/block/{height}/transaction", s.handleFlowBlockTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/transaction", s.handleFlowListTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/transaction/{id}", s.handleFlowGetTransaction).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account", s.handleFlowListAccounts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}", s.handleFlowGetAccount).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/contract/{name}", s.handleGetAccountContractCode).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/storage", s.handleGetAccountStorage).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/storage/links", s.handleGetAccountStorageLinks).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/storage/item", s.handleGetAccountStorageItem).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/transaction", s.handleFlowAccountTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/ft/transfer", s.handleFlowAccountFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/nft/transfer", s.handleFlowAccountNFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/ft/holding", s.handleFlowAccountFTHoldings).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/ft", s.handleFlowAccountFTVaults).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/ft/{token}", s.handleFlowAccountFTToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/ft/{token}/transfer", s.handleFlowAccountFTTokenTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/nft", s.handleFlowAccountNFTCollections).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/nft/{nft_type}", s.handleFlowAccountNFTByCollection).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/ft/transfer", s.handleFlowFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/ft", s.handleFlowListFTTokens).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/ft/{token}", s.handleFlowGetFTToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/ft/{token}/holding", s.handleFlowFTHoldingsByToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/ft/{token}/top-account", s.handleFlowTopFTAccounts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/ft/{token}/account/{address}", s.handleFlowAccountFTHoldingByToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/transfer", s.handleFlowNFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft", s.handleFlowListNFTCollections).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/{nft_type}", s.handleFlowGetNFTCollection).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/{nft_type}/holding", s.handleFlowNFTHoldingsByCollection).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/{nft_type}/top-account", s.handleFlowTopNFTAccounts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/search", s.handleFlowNFTSearch).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/{nft_type}/item", s.handleFlowNFTCollectionItems).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/{nft_type}/item/{id}", s.handleFlowNFTItem).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/{nft_type}/item/{id}/transfer", s.handleFlowNFTItemTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/nft/backfill", s.handleFlowNFTBackfill).Methods("POST", "OPTIONS")
	r.HandleFunc("/flow/coa/backfill", s.handleFlowCOABackfill).Methods("POST", "OPTIONS")
	r.HandleFunc("/flow/contract", s.handleFlowListContracts).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/contract/{identifier}", s.handleFlowGetContract).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/contract/{identifier}/transaction", s.handleContractTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/contract/{identifier}/version", s.handleContractVersionList).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/contract/{identifier}/version/{id}", s.handleFlowGetContractVersion).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/contract/{identifier}/{id}", s.handleFlowGetContractVersion).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/evm/transaction", s.handleFlowListEVMTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/evm/transaction/{hash}", s.handleFlowGetEVMTransaction).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/evm/token", s.handleFlowListEVMTokens).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/evm/token/{address}", s.handleFlowGetEVMToken).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/node", s.handleListNodes).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/node/{node_id}", s.handleGetNode).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/node/{node_id}/reward/delegation", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/scheduled-transaction", s.handleFlowScheduledTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/scheduled-transaction", s.handleFlowAccountScheduledTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/balance/history", s.handleFlowAccountBalanceHistory).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/tax-report", s.handleTaxReport).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/key/{publicKey}", s.handleFlowSearchByPublicKey).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/coa/{address}", s.handleGetCOAMapping).Methods("GET", "OPTIONS")
	r.HandleFunc("/flow/account/{address}/labels", s.handleFlowAccountLabels).Methods("GET", "OPTIONS")
}

func registerAccountingRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/accounting/account/{address}", s.handleFlowGetAccount).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/account/{address}/transaction", s.handleFlowAccountTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/account/{address}/ft/transfer", s.handleFlowAccountFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/account/{address}/nft", s.handleFlowAccountNFTCollections).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/account/{address}/ft", s.handleFlowAccountFTVaults).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/transaction", s.handleFlowListTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/transaction/{id}", s.handleFlowGetTransaction).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/nft/transfer", s.handleFlowNFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/accounting/account/{address}/tax-report", s.handleTaxReport).Methods("GET", "OPTIONS")
}

func registerStatusRoutes(r *mux.Router, s *Server) {
	r.HandleFunc("/status/count", s.handleStatusCount).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/stat", cachedHandler(5*time.Minute, s.handleStatusStat)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/stat/{timescale}/trend", cachedHandler(5*time.Minute, s.handleStatusStatTrend)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/flow/stat", cachedHandler(30*time.Second, s.handleStatusFlowStat)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/epoch/status", cachedHandler(60*time.Second, s.handleStatusEpochStatus)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/epoch/stat", cachedHandler(60*time.Second, s.handleStatusEpochStat)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/tokenomics", cachedHandler(60*time.Second, s.handleStatusTokenomics)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/price", cachedHandler(60*time.Second, s.handleStatusPrice)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/price/history", cachedHandler(5*time.Minute, s.handleStatusPriceHistory)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/nodes", cachedHandler(60*time.Second, s.handleStatusNodes)).Methods("GET", "OPTIONS")
	r.HandleFunc("/status/gcp-vms", s.handleStatusGCPVMs).Methods("GET", "OPTIONS")

	// Compatibility endpoints (find.xyz style)
	r.HandleFunc("/flowscan/v1/stats", s.handleCompatFlowscanStats).Methods("GET", "OPTIONS")
	r.HandleFunc("/public/v1/totalSupply", s.handleCompatTotalSupply).Methods("GET", "OPTIONS")
	r.HandleFunc("/public/v1/totalSupplyWithDecimal", s.handleCompatTotalSupplyWithDecimal).Methods("GET", "OPTIONS")
	r.HandleFunc("/public/v1/epoch/payout", s.handlePublicEpochPayout).Methods("GET", "OPTIONS")

	// Analytics endpoints (cached — slow queries, data changes infrequently)
	r.HandleFunc("/analytics/daily", cachedHandler(5*time.Minute, s.handleAnalyticsDaily)).Methods("GET", "OPTIONS")
	r.HandleFunc("/analytics/transfers/daily", cachedHandler(5*time.Minute, s.handleAnalyticsTransfersDaily)).Methods("GET", "OPTIONS")
}

func registerDeferredRoutes(r *mux.Router, s *Server) {
	// DeFi endpoints
	r.HandleFunc("/defi/asset", s.handleDefiListAssets).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/events", s.handleDefiListEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/latest-block", s.handleDefiLatestBlock).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/latest-swap", s.handleDefiLatestSwap).Methods("GET", "OPTIONS")
	r.HandleFunc("/defi/pair", s.handleDefiListPairs).Methods("GET", "OPTIONS")
	// Staking endpoints
	r.HandleFunc("/staking/delegator", s.handleStakingDelegators).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/account/{address}/ft/transfer", s.handleStakingAccountFTTransfers).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/account/{address}/transaction", s.handleStakingAccountTransactions).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/epoch/stats", cachedHandler(5*time.Minute, s.handleGetEpochStats)).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/epoch/{epoch}/nodes", s.handleListEpochNodes).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/epoch/{epoch}/role/{role}/nodes/aggregate", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/epoch/{epoch}/role/{role}/nodes/count", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/epoch/{epoch}/role/{role}/nodes/grouped", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/ft_transfer/{address}", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/node/{node_id}/event", s.handleGetNodeEvents).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/rewards/paid", s.handleStakingRewardsPaid).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/rewards/staking", s.handleStakingRewardsStaking).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/tokenomics", s.handleStakingTokenomics).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/transaction/address/{address}", s.handleNotImplemented).Methods("GET", "OPTIONS")
	r.HandleFunc("/staking/transaction/{transaction_id}", s.handleNotImplemented).Methods("GET", "OPTIONS")
}
