import { useState, useCallback, useMemo, useRef, useEffect } from 'react';
import { Loader2, Copy, Check, Download, AlertTriangle, Sparkles } from 'lucide-react';
import { ensureCodegenLoaded, analyzeCode, generateFromReport } from '../codegen/wasmLoader';
import type { CodegenLanguage, CodegenResult } from '../codegen/wasmLoader';
import { useShikiHighlighter, highlightCode } from '../hooks/useShiki';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface CodegenPanelProps {
  code: string;
  filename?: string;
  codeType: 'script' | 'transaction' | 'contract';
  onFixWithAI?: (errorMessage: string) => void;
}

const LANGUAGES: { key: CodegenLanguage; label: string; ext: string }[] = [
  { key: 'typescript', label: 'TypeScript', ext: '.ts' },
  { key: 'swift', label: 'Swift', ext: '.swift' },
  { key: 'go', label: 'Go', ext: '.go' },
  { key: 'python', label: 'Python', ext: '.py' },
  { key: 'kotlin', label: 'Kotlin', ext: '.kt' },
];

const SHIKI_LANG_MAP: Record<CodegenLanguage, string> = {
  typescript: 'typescript',
  swift: 'swift',
  go: 'go',
  python: 'python',
  kotlin: 'kotlin',
};

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }, [text]);

  return (
    <button
      onClick={handleCopy}
      className={`flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium rounded border transition-colors ${
        copied
          ? 'bg-emerald-900/50 text-emerald-400 border-emerald-700'
          : 'bg-zinc-800 text-zinc-500 border-zinc-700 hover:text-zinc-300 hover:border-zinc-600'
      }`}
      title="Copy to clipboard"
    >
      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
      {copied ? 'Copied' : 'Copy'}
    </button>
  );
}

function DownloadButton({ text, filename }: { text: string; filename: string }) {
  const handleDownload = useCallback(() => {
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }, [text, filename]);

  return (
    <button
      onClick={handleDownload}
      className="flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium rounded border transition-colors bg-zinc-800 text-zinc-500 border-zinc-700 hover:text-zinc-300 hover:border-zinc-600"
      title={`Download as ${filename}`}
    >
      <Download className="w-3 h-3" />
      {filename}
    </button>
  );
}

function LanguagePills({
  selected,
  onChange,
}: {
  selected: CodegenLanguage;
  onChange: (lang: CodegenLanguage) => void;
}) {
  return (
    <div className="flex items-center bg-zinc-800 rounded overflow-hidden border border-zinc-700">
      {LANGUAGES.map((lang) => (
        <button
          key={lang.key}
          onClick={() => onChange(lang.key)}
          className={`px-2 py-0.5 text-[10px] font-medium transition-colors ${
            selected === lang.key
              ? 'bg-zinc-700 text-zinc-100'
              : 'text-zinc-500 hover:text-zinc-300'
          }`}
        >
          {lang.label}
        </button>
      ))}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export default function CodegenPanel({ code, filename, codeType, onFixWithAI }: CodegenPanelProps) {
  const [language, setLanguage] = useState<CodegenLanguage>('typescript');
  // Per-language results + the cached analysis report JSON
  const [results, setResults] = useState<Partial<Record<CodegenLanguage, CodegenResult>>>({});
  const [reportCache, setReportCache] = useState<{ report: string; sourceCode: string } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const highlighter = useShikiHighlighter();
  const generatingRef = useRef(false);
  // Track whether we've auto-generated on mount
  const autoGeneratedRef = useRef(false);

  const isContract = codeType === 'contract';
  const isStale = reportCache !== null && reportCache.sourceCode !== code;
  const currentResult = results[language] ?? null;
  const hasOutput = currentResult && currentResult.code.length > 0;
  const hasError = currentResult && currentResult.error;

  // Generate for a single language, reusing cached report if source hasn't changed
  const generateForLanguage = useCallback(async (lang: CodegenLanguage, forceReanalyze = false) => {
    if (generatingRef.current || isContract || !code.trim()) return;
    generatingRef.current = true;
    setLoading(true);
    setError(null);

    try {
      await ensureCodegenLoaded();

      // Reuse cached report if source code hasn't changed
      let reportJSON: string;
      if (reportCache && reportCache.sourceCode === code && !forceReanalyze) {
        reportJSON = reportCache.report;
      } else {
        const analysis = analyzeCode(code, filename);
        if ('error' in analysis) {
          setError(analysis.error);
          setLoading(false);
          generatingRef.current = false;
          return;
        }
        reportJSON = analysis.report;
        setReportCache({ report: reportJSON, sourceCode: code });
        // Clear old results since source changed
        setResults({});
      }

      const result = generateFromReport(reportJSON, lang);
      setResults((prev) => ({ ...prev, [lang]: result }));
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Failed to load codegen WASM');
    } finally {
      setLoading(false);
      generatingRef.current = false;
    }
  }, [code, filename, isContract, reportCache]);

  // Auto-generate current language on mount (first render)
  useEffect(() => {
    if (autoGeneratedRef.current || isContract || !code.trim()) return;
    autoGeneratedRef.current = true;
    generateForLanguage(language);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // When language changes, generate if we don't have a result for it yet
  const handleLanguageChange = useCallback((lang: CodegenLanguage) => {
    setLanguage(lang);
    if (!results[lang] && !isContract && code.trim()) {
      generateForLanguage(lang);
    }
  }, [results, isContract, code, generateForLanguage]);

  // Manual regenerate (for stale or retry)
  const handleRegenerate = useCallback(() => {
    generateForLanguage(language, true);
  }, [language, generateForLanguage]);

  // Syntax-highlighted HTML
  const highlightedHtml = useMemo(() => {
    if (!highlighter || !currentResult?.code) return null;
    return highlightCode(highlighter, currentResult.code, SHIKI_LANG_MAP[language], 'cadence-editor');
  }, [highlighter, currentResult?.code, language]);

  // Download filename
  const downloadFilename = useMemo(() => {
    const base = filename?.replace(/\.(cdc|cadence)$/, '') || 'generated';
    const ext = LANGUAGES.find((l) => l.key === language)?.ext || '.ts';
    return `${base}${ext}`;
  }, [filename, language]);

  // Contract: show unsupported message
  if (isContract) {
    return (
      <div className="flex flex-col h-full min-h-0">
        <div className="flex items-center gap-2 px-3 py-1.5 border-b border-zinc-800 shrink-0">
          <LanguagePills selected={language} onChange={setLanguage} />
        </div>
        <div className="flex-1 flex items-center justify-center text-zinc-600 text-sm">
          Codegen is only available for scripts and transactions
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full min-h-0">
      {/* Toolbar */}
      <div className="flex items-center gap-2 px-3 py-1.5 border-b border-zinc-800 shrink-0">
        <LanguagePills selected={language} onChange={handleLanguageChange} />

        <div className="flex-1" />

        {hasOutput && <CopyButton text={currentResult!.code} />}
        {hasOutput && <DownloadButton text={currentResult!.code} filename={downloadFilename} />}
      </div>

      {/* Stale indicator */}
      {isStale && (
        <button
          onClick={handleRegenerate}
          className="flex items-center gap-1.5 px-3 py-1 bg-yellow-900/20 border-b border-yellow-800/30 text-yellow-500 text-[10px] hover:bg-yellow-900/30 transition-colors w-full text-left"
        >
          <AlertTriangle className="w-3 h-3" />
          Code changed — click to regenerate
        </button>
      )}

      {/* Content area */}
      <div className="flex-1 overflow-auto p-3 font-mono text-xs">
        {loading && (
          <div className="flex items-center justify-center h-full gap-2 text-zinc-500 text-sm">
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating...
          </div>
        )}

        {!loading && error && (
          <div className="rounded border border-red-800/50 bg-red-900/20 p-3">
            <p className="text-red-400">{error}</p>
            {onFixWithAI && (
              <button
                onClick={() => onFixWithAI(error)}
                className="mt-2 flex items-center gap-1.5 px-3 py-1 text-[11px] font-medium rounded bg-emerald-600 hover:bg-emerald-500 text-white transition-colors"
              >
                <Sparkles className="w-3.5 h-3.5" />
                Fix with AI
              </button>
            )}
          </div>
        )}

        {!loading && !error && hasError && (
          <div className="rounded border border-red-800/50 bg-red-900/20 p-3">
            <p className="text-red-400">{currentResult!.error}</p>
            {onFixWithAI && (
              <button
                onClick={() => onFixWithAI(currentResult!.error!)}
                className="mt-2 flex items-center gap-1.5 px-3 py-1 text-[11px] font-medium rounded bg-emerald-600 hover:bg-emerald-500 text-white transition-colors"
              >
                <Sparkles className="w-3.5 h-3.5" />
                Fix with AI
              </button>
            )}
          </div>
        )}

        {!loading && !error && hasOutput && (
          highlightedHtml ? (
            <div
              className="shiki-output [&_pre]:!bg-transparent [&_pre]:!p-0 [&_pre]:!m-0 [&_code]:!text-xs leading-relaxed"
              dangerouslySetInnerHTML={{ __html: highlightedHtml }}
            />
          ) : (
            <pre className="whitespace-pre-wrap break-all text-zinc-300 leading-relaxed">{currentResult!.code}</pre>
          )
        )}

        {!loading && !error && !hasOutput && !hasError && !currentResult && (
          <div className="flex items-center justify-center h-full text-zinc-600 text-sm">
            No output generated
          </div>
        )}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
