/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TxsIndexRouteImport } from './routes/txs/index'
import { Route as TxIndexRouteImport } from './routes/tx/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions/index'
import { Route as TokensIndexRouteImport } from './routes/tokens/index'
import { Route as ScheduledIndexRouteImport } from './routes/scheduled/index'
import { Route as NftsIndexRouteImport } from './routes/nfts/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as BlocksIndexRouteImport } from './routes/blocks/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as TxsTxIdRouteImport } from './routes/txs/$txId'
import { Route as TxTxIdRouteImport } from './routes/tx/$txId'
import { Route as TransactionsTxIdRouteImport } from './routes/transactions/$txId'
import { Route as TokensTokenRouteImport } from './routes/tokens/$token'
import { Route as NftsNftTypeRouteImport } from './routes/nfts/$nftType'
import { Route as KeyPublicKeyRouteImport } from './routes/key/$publicKey'
import { Route as ContractsIdRouteImport } from './routes/contracts/$id'
import { Route as BlocksHeightRouteImport } from './routes/blocks/$height'
import { Route as AccountsAddressRouteImport } from './routes/accounts/$address'
import { Route as NftsNftTypeItemIdRouteImport } from './routes/nfts/$nftType/item/$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TxsIndexRoute = TxsIndexRouteImport.update({
  id: '/txs/',
  path: '/txs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TxIndexRoute = TxIndexRouteImport.update({
  id: '/tx/',
  path: '/tx/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensIndexRoute = TokensIndexRouteImport.update({
  id: '/tokens/',
  path: '/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledIndexRoute = ScheduledIndexRouteImport.update({
  id: '/scheduled/',
  path: '/scheduled/',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsIndexRoute = NftsIndexRouteImport.update({
  id: '/nfts/',
  path: '/nfts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TxsTxIdRoute = TxsTxIdRouteImport.update({
  id: '/txs/$txId',
  path: '/txs/$txId',
  getParentRoute: () => rootRouteImport,
} as any)
const TxTxIdRoute = TxTxIdRouteImport.update({
  id: '/tx/$txId',
  path: '/tx/$txId',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTxIdRoute = TransactionsTxIdRouteImport.update({
  id: '/transactions/$txId',
  path: '/transactions/$txId',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensTokenRoute = TokensTokenRouteImport.update({
  id: '/tokens/$token',
  path: '/tokens/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsNftTypeRoute = NftsNftTypeRouteImport.update({
  id: '/nfts/$nftType',
  path: '/nfts/$nftType',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyPublicKeyRoute = KeyPublicKeyRouteImport.update({
  id: '/key/$publicKey',
  path: '/key/$publicKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksHeightRoute = BlocksHeightRouteImport.update({
  id: '/blocks/$height',
  path: '/blocks/$height',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAddressRoute = AccountsAddressRouteImport.update({
  id: '/accounts/$address',
  path: '/accounts/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsNftTypeItemIdRoute = NftsNftTypeItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => NftsNftTypeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/nodes': typeof NodesRoute
  '/stats': typeof StatsRoute
  '/accounts/$address': typeof AccountsAddressRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/key/$publicKey': typeof KeyPublicKeyRoute
  '/nfts/$nftType': typeof NftsNftTypeRouteWithChildren
  '/tokens/$token': typeof TokensTokenRoute
  '/transactions/$txId': typeof TransactionsTxIdRoute
  '/tx/$txId': typeof TxTxIdRoute
  '/txs/$txId': typeof TxsTxIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/nfts/': typeof NftsIndexRoute
  '/scheduled/': typeof ScheduledIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/tx/': typeof TxIndexRoute
  '/txs/': typeof TxsIndexRoute
  '/nfts/$nftType/item/$id': typeof NftsNftTypeItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/nodes': typeof NodesRoute
  '/stats': typeof StatsRoute
  '/accounts/$address': typeof AccountsAddressRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/key/$publicKey': typeof KeyPublicKeyRoute
  '/nfts/$nftType': typeof NftsNftTypeRouteWithChildren
  '/tokens/$token': typeof TokensTokenRoute
  '/transactions/$txId': typeof TransactionsTxIdRoute
  '/tx/$txId': typeof TxTxIdRoute
  '/txs/$txId': typeof TxsTxIdRoute
  '/accounts': typeof AccountsIndexRoute
  '/blocks': typeof BlocksIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/nfts': typeof NftsIndexRoute
  '/scheduled': typeof ScheduledIndexRoute
  '/tokens': typeof TokensIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/tx': typeof TxIndexRoute
  '/txs': typeof TxsIndexRoute
  '/nfts/$nftType/item/$id': typeof NftsNftTypeItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/nodes': typeof NodesRoute
  '/stats': typeof StatsRoute
  '/accounts/$address': typeof AccountsAddressRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/key/$publicKey': typeof KeyPublicKeyRoute
  '/nfts/$nftType': typeof NftsNftTypeRouteWithChildren
  '/tokens/$token': typeof TokensTokenRoute
  '/transactions/$txId': typeof TransactionsTxIdRoute
  '/tx/$txId': typeof TxTxIdRoute
  '/txs/$txId': typeof TxsTxIdRoute
  '/accounts/': typeof AccountsIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/nfts/': typeof NftsIndexRoute
  '/scheduled/': typeof ScheduledIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/tx/': typeof TxIndexRoute
  '/txs/': typeof TxsIndexRoute
  '/nfts/$nftType/item/$id': typeof NftsNftTypeItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/api-docs'
    | '/nodes'
    | '/stats'
    | '/accounts/$address'
    | '/blocks/$height'
    | '/contracts/$id'
    | '/key/$publicKey'
    | '/nfts/$nftType'
    | '/tokens/$token'
    | '/transactions/$txId'
    | '/tx/$txId'
    | '/txs/$txId'
    | '/accounts/'
    | '/blocks/'
    | '/contracts/'
    | '/nfts/'
    | '/scheduled/'
    | '/tokens/'
    | '/transactions/'
    | '/tx/'
    | '/txs/'
    | '/nfts/$nftType/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/api-docs'
    | '/nodes'
    | '/stats'
    | '/accounts/$address'
    | '/blocks/$height'
    | '/contracts/$id'
    | '/key/$publicKey'
    | '/nfts/$nftType'
    | '/tokens/$token'
    | '/transactions/$txId'
    | '/tx/$txId'
    | '/txs/$txId'
    | '/accounts'
    | '/blocks'
    | '/contracts'
    | '/nfts'
    | '/scheduled'
    | '/tokens'
    | '/transactions'
    | '/tx'
    | '/txs'
    | '/nfts/$nftType/item/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/api-docs'
    | '/nodes'
    | '/stats'
    | '/accounts/$address'
    | '/blocks/$height'
    | '/contracts/$id'
    | '/key/$publicKey'
    | '/nfts/$nftType'
    | '/tokens/$token'
    | '/transactions/$txId'
    | '/tx/$txId'
    | '/txs/$txId'
    | '/accounts/'
    | '/blocks/'
    | '/contracts/'
    | '/nfts/'
    | '/scheduled/'
    | '/tokens/'
    | '/transactions/'
    | '/tx/'
    | '/txs/'
    | '/nfts/$nftType/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  ApiDocsRoute: typeof ApiDocsRoute
  NodesRoute: typeof NodesRoute
  StatsRoute: typeof StatsRoute
  AccountsAddressRoute: typeof AccountsAddressRoute
  BlocksHeightRoute: typeof BlocksHeightRoute
  ContractsIdRoute: typeof ContractsIdRoute
  KeyPublicKeyRoute: typeof KeyPublicKeyRoute
  NftsNftTypeRoute: typeof NftsNftTypeRouteWithChildren
  TokensTokenRoute: typeof TokensTokenRoute
  TransactionsTxIdRoute: typeof TransactionsTxIdRoute
  TxTxIdRoute: typeof TxTxIdRoute
  TxsTxIdRoute: typeof TxsTxIdRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  NftsIndexRoute: typeof NftsIndexRoute
  ScheduledIndexRoute: typeof ScheduledIndexRoute
  TokensIndexRoute: typeof TokensIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  TxIndexRoute: typeof TxIndexRoute
  TxsIndexRoute: typeof TxsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/txs/': {
      id: '/txs/'
      path: '/txs'
      fullPath: '/txs/'
      preLoaderRoute: typeof TxsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tx/': {
      id: '/tx/'
      path: '/tx'
      fullPath: '/tx/'
      preLoaderRoute: typeof TxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/': {
      id: '/tokens/'
      path: '/tokens'
      fullPath: '/tokens/'
      preLoaderRoute: typeof TokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled/': {
      id: '/scheduled/'
      path: '/scheduled'
      fullPath: '/scheduled/'
      preLoaderRoute: typeof ScheduledIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/': {
      id: '/nfts/'
      path: '/nfts'
      fullPath: '/nfts/'
      preLoaderRoute: typeof NftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/txs/$txId': {
      id: '/txs/$txId'
      path: '/txs/$txId'
      fullPath: '/txs/$txId'
      preLoaderRoute: typeof TxsTxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tx/$txId': {
      id: '/tx/$txId'
      path: '/tx/$txId'
      fullPath: '/tx/$txId'
      preLoaderRoute: typeof TxTxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$txId': {
      id: '/transactions/$txId'
      path: '/transactions/$txId'
      fullPath: '/transactions/$txId'
      preLoaderRoute: typeof TransactionsTxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$token': {
      id: '/tokens/$token'
      path: '/tokens/$token'
      fullPath: '/tokens/$token'
      preLoaderRoute: typeof TokensTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/$nftType': {
      id: '/nfts/$nftType'
      path: '/nfts/$nftType'
      fullPath: '/nfts/$nftType'
      preLoaderRoute: typeof NftsNftTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key/$publicKey': {
      id: '/key/$publicKey'
      path: '/key/$publicKey'
      fullPath: '/key/$publicKey'
      preLoaderRoute: typeof KeyPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$height': {
      id: '/blocks/$height'
      path: '/blocks/$height'
      fullPath: '/blocks/$height'
      preLoaderRoute: typeof BlocksHeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$address': {
      id: '/accounts/$address'
      path: '/accounts/$address'
      fullPath: '/accounts/$address'
      preLoaderRoute: typeof AccountsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts/$nftType/item/$id': {
      id: '/nfts/$nftType/item/$id'
      path: '/item/$id'
      fullPath: '/nfts/$nftType/item/$id'
      preLoaderRoute: typeof NftsNftTypeItemIdRouteImport
      parentRoute: typeof NftsNftTypeRoute
    }
  }
}

interface NftsNftTypeRouteChildren {
  NftsNftTypeItemIdRoute: typeof NftsNftTypeItemIdRoute
}

const NftsNftTypeRouteChildren: NftsNftTypeRouteChildren = {
  NftsNftTypeItemIdRoute: NftsNftTypeItemIdRoute,
}

const NftsNftTypeRouteWithChildren = NftsNftTypeRoute._addFileChildren(
  NftsNftTypeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  ApiDocsRoute: ApiDocsRoute,
  NodesRoute: NodesRoute,
  StatsRoute: StatsRoute,
  AccountsAddressRoute: AccountsAddressRoute,
  BlocksHeightRoute: BlocksHeightRoute,
  ContractsIdRoute: ContractsIdRoute,
  KeyPublicKeyRoute: KeyPublicKeyRoute,
  NftsNftTypeRoute: NftsNftTypeRouteWithChildren,
  TokensTokenRoute: TokensTokenRoute,
  TransactionsTxIdRoute: TransactionsTxIdRoute,
  TxTxIdRoute: TxTxIdRoute,
  TxsTxIdRoute: TxsTxIdRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  NftsIndexRoute: NftsIndexRoute,
  ScheduledIndexRoute: ScheduledIndexRoute,
  TokensIndexRoute: TokensIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  TxIndexRoute: TxIndexRoute,
  TxsIndexRoute: TxsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
