package repository

import "testing"

func TestNormalizeScript(t *testing.T) {
	tests := []struct {
		name   string
		a, b   string
		expect bool // true = should produce same normalized output
	}{
		{
			name: "identical scripts",
			a:    `import FungibleToken from 0xf233dcee88fe0abe`,
			b:    `import FungibleToken from 0xf233dcee88fe0abe`,
			expect: true,
		},
		{
			name: "different leading comment",
			a:    "// Version 1\nimport FungibleToken from 0xf233dcee88fe0abe\ntransaction { execute {} }",
			b:    "// Version 2 — updated\nimport FungibleToken from 0xf233dcee88fe0abe\ntransaction { execute {} }",
			expect: true,
		},
		{
			name: "block comment vs no comment",
			a:    "/* generated by tool v3 */\nimport FungibleToken from 0xf233dcee88fe0abe",
			b:    "import FungibleToken from 0xf233dcee88fe0abe",
			expect: true,
		},
		{
			name: "different whitespace",
			a:    "import  FungibleToken  from   0xf233dcee88fe0abe",
			b:    "import FungibleToken from 0xf233dcee88fe0abe",
			expect: true,
		},
		{
			name: "actually different scripts",
			a:    "import FungibleToken from 0xf233dcee88fe0abe\ntransaction { execute {} }",
			b:    "import NonFungibleToken from 0x1d7e57aa55817448\ntransaction { execute {} }",
			expect: false,
		},
		{
			name: "comment inside string preserved",
			a:    `let msg = "// not a comment"`,
			b:    `let msg = "// not a comment"`,
			expect: true,
		},
		{
			name: "comment inside string differs from stripped",
			a:    `let msg = "// not a comment"`,
			b:    `let msg = ""`,
			expect: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			na := NormalizeScript(tc.a)
			nb := NormalizeScript(tc.b)
			same := na == nb
			if same != tc.expect {
				t.Errorf("expected same=%v, got same=%v\n  normalized a: %q\n  normalized b: %q", tc.expect, same, na, nb)
			}
		})
	}
}

func TestNormalizedScriptHash(t *testing.T) {
	a := "// comment A\nimport Foo from 0x1234"
	b := "// comment B\nimport Foo from 0x1234"
	if NormalizedScriptHash(a) != NormalizedScriptHash(b) {
		t.Error("scripts differing only in comments should have the same normalized hash")
	}
	if NormalizedScriptHash(a) == "" {
		t.Error("hash should not be empty")
	}
}
